package org.acumen.training.codes.model;
// Generated Oct 24, 2024, 2:15:02 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * SectionId generated by hbm2java
 */
@Embeddable
public class SectionId {

	private String courseId;
	private String secId;
	private String semester;
	private short year;

	public SectionId() {
	}

	public SectionId(String courseId, String secId, String semester, short year) {
		this.courseId = courseId;
		this.secId = secId;
		this.semester = semester;
		this.year = year;
	}

	@Column(name = "course_id", nullable = false, length = 8)
	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	@Column(name = "sec_id", nullable = false, length = 8)
	public String getSecId() {
		return this.secId;
	}

	public void setSecId(String secId) {
		this.secId = secId;
	}

	@Column(name = "semester", nullable = false, length = 6)
	public String getSemester() {
		return this.semester;
	}

	public void setSemester(String semester) {
		this.semester = semester;
	}

	@Column(name = "year", nullable = false, precision = 4, scale = 0)
	public short getYear() {
		return this.year;
	}

	public void setYear(short year) {
		this.year = year;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SectionId))
			return false;
		SectionId castOther = (SectionId) other;

		return ((this.getCourseId() == castOther.getCourseId()) || (this.getCourseId() != null
				&& castOther.getCourseId() != null && this.getCourseId().equals(castOther.getCourseId())))
				&& ((this.getSecId() == castOther.getSecId()) || (this.getSecId() != null
						&& castOther.getSecId() != null && this.getSecId().equals(castOther.getSecId())))
				&& ((this.getSemester() == castOther.getSemester()) || (this.getSemester() != null
						&& castOther.getSemester() != null && this.getSemester().equals(castOther.getSemester())))
				&& (this.getYear() == castOther.getYear());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCourseId() == null ? 0 : this.getCourseId().hashCode());
		result = 37 * result + (getSecId() == null ? 0 : this.getSecId().hashCode());
		result = 37 * result + (getSemester() == null ? 0 : this.getSemester().hashCode());
		result = 37 * result + this.getYear();
		return result;
	}

}
