package org.acumen.training.codes.model;
// Generated Oct 24, 2024, 2:15:02 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * TimeSlotId generated by hbm2java
 */
@Embeddable
public class TimeSlotId {

	private String timeSlotId;
	private String day;
	private byte startHr;
	private byte startMin;

	public TimeSlotId() {
	}

	public TimeSlotId(String timeSlotId, String day, byte startHr, byte startMin) {
		this.timeSlotId = timeSlotId;
		this.day = day;
		this.startHr = startHr;
		this.startMin = startMin;
	}

	@Column(name = "time_slot_id", nullable = false, length = 4)
	public String getTimeSlotId() {
		return this.timeSlotId;
	}

	public void setTimeSlotId(String timeSlotId) {
		this.timeSlotId = timeSlotId;
	}

	@Column(name = "day", nullable = false, length = 1)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Column(name = "start_hr", nullable = false, precision = 2, scale = 0)
	public byte getStartHr() {
		return this.startHr;
	}

	public void setStartHr(byte startHr) {
		this.startHr = startHr;
	}

	@Column(name = "start_min", nullable = false, precision = 2, scale = 0)
	public byte getStartMin() {
		return this.startMin;
	}

	public void setStartMin(byte startMin) {
		this.startMin = startMin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TimeSlotId))
			return false;
		TimeSlotId castOther = (TimeSlotId) other;

		return ((this.getTimeSlotId() == castOther.getTimeSlotId()) || (this.getTimeSlotId() != null
				&& castOther.getTimeSlotId() != null && this.getTimeSlotId().equals(castOther.getTimeSlotId())))
				&& ((this.getDay() == castOther.getDay()) || (this.getDay() != null && castOther.getDay() != null
						&& this.getDay().equals(castOther.getDay())))
				&& (this.getStartHr() == castOther.getStartHr()) && (this.getStartMin() == castOther.getStartMin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTimeSlotId() == null ? 0 : this.getTimeSlotId().hashCode());
		result = 37 * result + (getDay() == null ? 0 : this.getDay().hashCode());
		result = 37 * result + this.getStartHr();
		result = 37 * result + this.getStartMin();
		return result;
	}

}
