package org.acumen.training.codes.model;
// Generated Oct 24, 2024, 1:18:03 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Allowance generated by hbm2java
 */
@Entity
@Table(name = "allowance", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "id"))
public class Allowance implements java.io.Serializable {

	private int allowanceid;
	private int id;

	public Allowance() {
	}

	public Allowance(int allowanceid, int id) {
		this.allowanceid = allowanceid;
		this.id = id;
	}

	@Id

	@Column(name = "allowanceid", unique = true, nullable = false)
	public int getAllowanceid() {
		return this.allowanceid;
	}

	public void setAllowanceid(int allowanceid) {
		this.allowanceid = allowanceid;
	}

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
