package org.acumen.training.codes.model;
// Generated Oct 24, 2024, 1:18:03 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * DataTypes generated by hbm2java
 */
@Entity
@Table(name = "data_types", schema = "public")
public class DataTypes implements java.io.Serializable {

	private DataTypesId id;

	public DataTypes() {
	}

	public DataTypes(DataTypesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "age", column = @Column(name = "age", nullable = false)),
			@AttributeOverride(name = "emp", column = @Column(name = "emp", nullable = false)),
			@AttributeOverride(name = "popsize", column = @Column(name = "popsize", nullable = false)),
			@AttributeOverride(name = "salary", column = @Column(name = "salary", nullable = false, precision = 17, scale = 17)),
			@AttributeOverride(name = "accountAmount", column = @Column(name = "account_amount", precision = 8, scale = 8)),
			@AttributeOverride(name = "donation", column = @Column(name = "donation", nullable = false, precision = 0, scale = 0)),
			@AttributeOverride(name = "mortage", column = @Column(name = "mortage", nullable = false, precision = 10, scale = 3)),
			@AttributeOverride(name = "nickname", column = @Column(name = "nickname", nullable = false, length = 10)),
			@AttributeOverride(name = "position", column = @Column(name = "position", nullable = false, length = 200)),
			@AttributeOverride(name = "comment", column = @Column(name = "comment", nullable = false)),
			@AttributeOverride(name = "isemployeed", column = @Column(name = "isemployeed", nullable = false)),
			@AttributeOverride(name = "timein", column = @Column(name = "timein", nullable = false, length = 15)),
			@AttributeOverride(name = "birthday", column = @Column(name = "birthday", nullable = false, length = 13)),
			@AttributeOverride(name = "dateresigned", column = @Column(name = "dateresigned", nullable = false, length = 29)),
			@AttributeOverride(name = "moneytxdate", column = @Column(name = "moneytxdate", nullable = false, length = 35)),
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "amount", column = @Column(name = "amount", nullable = false, scale = 0)),
			@AttributeOverride(name = "isturnoff", column = @Column(name = "isturnoff", nullable = false)),
			@AttributeOverride(name = "picture", column = @Column(name = "picture", nullable = false)) })
	public DataTypesId getId() {
		return this.id;
	}

	public void setId(DataTypesId id) {
		this.id = id;
	}

}
