package org.acumen.training.codes.model;
// Generated Oct 24, 2024, 1:18:03 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Developer generated by hbm2java
 */
@Entity
@Table(name = "developer", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "empid"))
public class Developer implements java.io.Serializable {

	private int id;
	private Manager manager;
	private int empid;

	public Developer() {
	}

	public Developer(int id, int empid) {
		this.id = id;
		this.empid = empid;
	}

	public Developer(int id, Manager manager, int empid) {
		this.id = id;
		this.manager = manager;
		this.empid = empid;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "devid")
	public Manager getManager() {
		return this.manager;
	}

	public void setManager(Manager manager) {
		this.manager = manager;
	}

	@Column(name = "empid", unique = true, nullable = false)
	public int getEmpid() {
		return this.empid;
	}

	public void setEmpid(int empid) {
		this.empid = empid;
	}

}
