package org.acumen.training.codes.model;
// Generated Oct 24, 2024, 1:18:03 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Insurance generated by hbm2java
 */
@Entity
@Table(name = "insurance", schema = "public")
public class Insurance implements java.io.Serializable {

	private InsuranceId id;

	public Insurance() {
	}

	public Insurance(InsuranceId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "policyid", column = @Column(name = "policyid", nullable = false)),
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)) })
	public InsuranceId getId() {
		return this.id;
	}

	public void setId(InsuranceId id) {
		this.id = id;
	}

}
