package org.acumen.training.codes.model;
// Generated Oct 24, 2024, 1:18:03 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * InsuranceId generated by hbm2java
 */
@Embeddable
public class InsuranceId implements java.io.Serializable {

	private int policyid;
	private int id;

	public InsuranceId() {
	}

	public InsuranceId(int policyid, int id) {
		this.policyid = policyid;
		this.id = id;
	}

	@Column(name = "policyid", nullable = false)
	public int getPolicyid() {
		return this.policyid;
	}

	public void setPolicyid(int policyid) {
		this.policyid = policyid;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InsuranceId))
			return false;
		InsuranceId castOther = (InsuranceId) other;

		return (this.getPolicyid() == castOther.getPolicyid()) && (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPolicyid();
		result = 37 * result + this.getId();
		return result;
	}

}
