package org.acumen.training.codes.model;
// Generated Oct 24, 2024, 1:18:03 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Manager generated by hbm2java
 */
@Entity
@Table(name = "manager", schema = "public")
public class Manager implements java.io.Serializable {

	private int id;
	private String firstname;
	private char gender;
	private int age;
	private double salary;
	private Date birthday;
	private Set developers = new HashSet(0);

	public Manager() {
	}

	public Manager(int id, String firstname, char gender, int age, double salary, Date birthday) {
		this.id = id;
		this.firstname = firstname;
		this.gender = gender;
		this.age = age;
		this.salary = salary;
		this.birthday = birthday;
	}

	public Manager(int id, String firstname, char gender, int age, double salary, Date birthday, Set developers) {
		this.id = id;
		this.firstname = firstname;
		this.gender = gender;
		this.age = age;
		this.salary = salary;
		this.birthday = birthday;
		this.developers = developers;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "firstname", nullable = false, length = 100)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "gender", nullable = false, length = 1)
	public char getGender() {
		return this.gender;
	}

	public void setGender(char gender) {
		this.gender = gender;
	}

	@Column(name = "age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "salary", nullable = false, precision = 17, scale = 17)
	public double getSalary() {
		return this.salary;
	}

	public void setSalary(double salary) {
		this.salary = salary;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", nullable = false, length = 13)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "manager")
	public Set getDevelopers() {
		return this.developers;
	}

	public void setDevelopers(Set developers) {
		this.developers = developers;
	}

}
